### ISSUE TITLE
Getting an error on the second mapping question

### ISSUE THREAD

**Issue by djosephsen** [rjz/jq-tutorial#2]
Hi, thanks for this! 

I'm encountering an error on OSX 10.9.5 with jq 1.5, where my solution is giving the correct output, the tutorial's built-in solution is generating a parse error from jq: 

```
Given:    'products' (type "data?" to view)
Challenge: Return all products, but double their prices

> map({name, price: (.price*2)})

Expected:
jq: error: syntax error, unexpected ':' (Unix shell quoting issues?) at <top-level>, line 1:
map({ name, (price: .price * 2) })
jq: 1 compile error


Your answer:
[
  {
    "name": "Table",
    "price": 540
  },
  {
    "name": "Chair",
    "price": 300
  },
  {
    "name": "Desk",
    "price": 150
  },
  {
    "name": "Sofa",
    "price": 400
  },
  {
    "name": "Bookshelf",
    "price": 80
  }
]
```
It looks like a difference between how we're wrapping the price filter.  Anyway thought you should know. 

Thanks again! 

-dave

**Comment by rjz** [comment]
@djosephsen, huge thanks for reporting! Looks like this was actually fixed in https://github.com/rjz/jq-tutorial/commit/6e1cbb836, but never made it out to npm.

Republishing now—thanks again!
